"""
Trading backtest on ROLLING (genuinely out-of-sample) residuals.

Replaces 05_trading.py's static-fit residuals with the rolling residuals from
03b_rolling.py. AE-3 and PCA-3 residuals are now generated by models that never
saw the week being traded. Nelson-Siegel is cross-sectional OLS per date (already
rolling). Trend-follow uses a 1-week lookback to match the paper.

Two holding conventions:
  - 1-week  (primary; uses every weekly observation)
  - 4-week  (overlapping; effective position = trailing-4-week average of the
             weekly signal, the standard overlapping-claims construction)

PnL per bond per week ~ -tau * Delta y_t * position_{t-1}.
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import os

# --- Paths (resolved relative to this script; see 03b_rolling.py for layout) ---
_HERE = Path(__file__).resolve().parent
OUT = Path(os.environ.get("COURSEWORK_DIR", _HERE.parent))
RES = OUT / "results"
FIG = OUT / "figures"
FIG.mkdir(parents=True, exist_ok=True)

TENORS = ["2Y", "3Y", "5Y", "7Y", "10Y", "20Y"]
TAU = np.array([2.0, 3.0, 5.0, 7.0, 10.0, 20.0])
OOS_START = pd.Timestamp("2020-01-01")


def load_inputs():
    weekly = pd.read_csv(RES / "weekly_yields.csv", index_col="Date", parse_dates=True)[TENORS]
    ae  = pd.read_csv(RES / "rolling_ae3_residuals.csv",  index_col="Date", parse_dates=True)[TENORS]
    pca = pd.read_csv(RES / "rolling_pca3_residuals.csv", index_col="Date", parse_dates=True)[TENORS]
    # NS residual = actual - NS fit, full sample
    ns_recon = pd.read_csv(RES / "ns_reconstruction.csv", index_col="Date", parse_dates=True)[TENORS]
    common = weekly.index.intersection(ns_recon.index)
    ns = (weekly.loc[common] - ns_recon.loc[common])
    # align everything to the rolling residual window
    idx = ae.index.intersection(pca.index).intersection(weekly.index).intersection(ns.index)
    return weekly.loc[idx], ae.loc[idx], pca.loc[idx], ns.loc[idx]


def positions_from_residual(resid):
    return np.sign(resid)

def positions_trend(weekly, lookback=1):
    return -np.sign(weekly - weekly.shift(lookback))

def backtest(weekly, positions, holding=1):
    dy = weekly.diff()
    if holding == 1:
        pos_eff = positions.shift(1)
    else:
        # overlapping: effective position = trailing average of the weekly signal
        pos_eff = positions.rolling(holding).mean().shift(1)
    pnl_each = (-TAU * dy * pos_eff).dropna(how="any")
    pnl_port = pnl_each.mean(axis=1)
    return pnl_each, pnl_each.cumsum(), pnl_port, pnl_port.cumsum()

def stats(pnl, ann=52):
    mu = pnl.mean() * ann
    sd = pnl.std() * np.sqrt(ann)
    sr = mu / sd if sd > 0 else np.nan
    return pd.Series({"AnnRet(%)": mu, "AnnVol": sd, "Sharpe": sr,
                      "Hit": (pnl > 0).mean(),
                      "MaxDD": (pnl.cumsum() - pnl.cumsum().cummax()).min()})


def main():
    weekly, ae, pca, ns = load_inputs()
    print(f"Backtest window (rolling-OOS): {weekly.index.min().date()} -> {weekly.index.max().date()}  ({len(weekly)} weeks)\n")

    strategies = {
        "AE-3":  positions_from_residual(ae),
        "PCA-3": positions_from_residual(pca),
        "NS":    positions_from_residual(ns),
        "Trend": positions_trend(weekly, lookback=1),
    }

    # ---- portfolio table, 1-week holding ----
    rows = []
    results = {}
    for name, pos in strategies.items():
        pe, ce, pp, cp = backtest(weekly, pos, holding=1)
        results[name] = dict(pnl_each=pe, cum_each=ce, pnl_port=pp, cum_port=cp)
        for lbl, mask in [("Full (98-23 OOS)", pp.index == pp.index),
                          ("1998-2019", pp.index < OOS_START),
                          ("2020+",     pp.index >= OOS_START)]:
            s = stats(pp[mask]); s.name = (name, lbl); rows.append(s)
    port = pd.concat(rows, axis=1).T
    port.index = pd.MultiIndex.from_tuples(port.index, names=["Strategy", "Sample"])
    port.to_csv(RES / "rolling_trading_portfolio.csv")
    print("Portfolio Sharpe (rolling-OOS residuals, 1-week holding):")
    print(port["Sharpe"].unstack("Sample").reindex(["AE-3","PCA-3","NS","Trend"])
          [["1998-2019","2020+","Full (98-23 OOS)"]].round(3).to_string())

    # ---- by maturity, AE-3, 1-week ----
    rows = []
    for tenor in TENORS:
        s = stats(results["AE-3"]["pnl_each"][tenor]); s.name = tenor; rows.append(s)
    bymat = pd.concat(rows, axis=1).T
    bymat.to_csv(RES / "rolling_trading_bymaturity.csv")
    print("\nAE-3 Sharpe by maturity (rolling-OOS, full window):")
    print(bymat["Sharpe"].round(3).to_string())

    # ---- holding-period robustness (portfolio Sharpe, full window) ----
    print("\nHolding-period sensitivity (AE-3 portfolio Sharpe, full window):")
    for h in [1, 4]:
        _, _, pp, _ = backtest(weekly, strategies["AE-3"], holding=h)
        print(f"  {h}-week holding: {stats(pp)['Sharpe']:.3f}")

    # ---- Figure ----
    fig, axes = plt.subplots(1, 2, figsize=(11, 4))
    colors = {"AE-3":"#e41a1c","PCA-3":"#377eb8","NS":"#4daf4a","Trend":"#984ea3"}
    ax = axes[0]
    for name, r in results.items():
        ax.plot(r["cum_port"].index, r["cum_port"].values, lw=1.1, label=name, color=colors[name])
    ax.axhline(0, color="k", lw=0.5)
    ax.axvspan(OOS_START, weekly.index.max(), color="grey", alpha=0.15)
    ax.set_title("(a) Rolling-OOS portfolio, equal-weight, 1-week holding")
    ax.set_ylabel("Cumulative return (duration-weighted, %)")
    ax.legend(loc="upper left"); ax.grid(alpha=0.3)

    ax = axes[1]
    ce = results["AE-3"]["cum_each"]
    for tenor, c in zip(TENORS, plt.cm.viridis(np.linspace(0,0.9,len(TENORS)))):
        ax.plot(ce.index, ce[tenor].values, lw=0.9, color=c, label=tenor)
    ax.axhline(0, color="k", lw=0.5)
    ax.axvspan(OOS_START, weekly.index.max(), color="grey", alpha=0.15)
    ax.set_title("(b) Rolling-OOS AE-3 strategy by maturity")
    ax.set_ylabel("Cumulative return (%)")
    ax.legend(ncol=3, fontsize=9, loc="upper left"); ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(FIG / "fig_report_3_rolling.png", dpi=170, bbox_inches="tight")
    plt.close(fig)
    print(f"\nSaved {FIG / 'fig_report_3_rolling.png'}")


if __name__ == "__main__":
    main()
